spring.application.name=Clase-SPBOOT

# Configuraci�n de la URL, usuario y contrase�a de la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/productosjpa
spring.datasource.username=postgres
spring.datasource.password=123456

# Configuraci�n de JPA / Hibernate
# update: crea o modifica las tablas autom�ticamente seg�n tus clases de Java
# Configuraci�n de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false