spring.application.name=Clase-SPBOOT

# Configuración de la URL, usuario y contraseña de la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/productosjpa
spring.datasource.username=postgres
spring.datasource.password=123456

# Configuración de JPA / Hibernate
# update: crea o modifica las tablas automáticamente según tus clases de Java
# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false